2019-05-25 16:06:49,702 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-25 16:13:01,216 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-26 10:55:30,588 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-26 10:55:39,860 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-27 06:20:08,352 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-27 06:30:41,894 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-27 06:33:09,809 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-27 06:35:22,101 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-27 06:37:43,457 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-27 06:44:34,233 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-28 06:33:24,341 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-28 06:34:38,219 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-28 06:43:08,549 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-30 11:02:36,024 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-30 11:02:42,640 ERROR: Exception on /index [GET] [in /home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/chad/microblog/app/routes.py", line 31, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-05-30 11:04:00,392 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-30 11:07:06,574 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-30 11:09:42,022 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-31 06:09:03,304 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:47]
2019-05-31 06:12:22,557 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:47]
2019-05-31 06:17:59,531 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:47]
2019-05-31 06:18:55,895 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:47]
2019-05-31 06:29:10,819 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:47]
2019-05-31 06:29:15,842 ERROR: Exception on /login [GET] [in /home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chad/microblog/app/routes.py", line 55, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/chad/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/chad/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/chad/microblog/app/templates/login.html", line 26, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2019-05-31 06:29:24,673 ERROR: Exception on /login [GET] [in /home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chad/microblog/app/routes.py", line 55, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/chad/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/chad/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/chad/microblog/app/templates/login.html", line 26, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
